[features]
seeds = false
skip-lint = false
[programs.localnet]
anchor_token = "5iAVPXH9djWQbviQXbYvicsxums6Nf8zGiitGwGWu6QQ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/johnliu/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
